### ISSUE TITLE
Json Pointer should start with slash

### ISSUE THREAD

**Issue by lordofthejars** [fge/jackson-coreutils#4]
Hi I have been inspecting this test https://github.com/fge/jackson-coreutils/blob/master/src/test/java/com/github/fge/jackson/jsonpointer/ReferenceTokenTest.java#L133 and I have seen that you are testing json pointer expressions like:

`~0user` or `~1var~1lib~1mysql` but for what I have read on rfc, any json pointer should start with a slash `/`

 json-pointer    = *( "/" reference-token )

But maybe I am wrong and the test isn't testing this scenario.

**Comment by fge** [comment]
The `ReferenceToken` class will parse only a single reference token, that is, any part between slashes (including empty).

The method which parses a full JSON Pointer is `tokensFromInput()` in class `TreePointer`.

You may have noted that this class is supposed to go over all of `TreeNode`s... When I first asked tatu about this he said that would be nice...

And it turns out he has only implemented it for `JsonNode`. Ohwell...

Of course, it means you can simplify the whole stuff so as to only be valid for `JsonNode`s.

**Comment by lordofthejars** [comment]
Ok thanks anyway all expressions with a slash at first has worked perfectly in Json Node :D

**Comment by fge** [comment]
Not sure what you meant with that last comment? I only know that I have tested my implementation pretty thoroughly ;)
